// front/src/components/DirItem.vue
<script setup lang="ts">
import { toRefs } from 'vue';
import { FileItem } from './FileItem';
const props = defineProps<FileItem>()
const { name, queryUrl } = toRefs(props);
</script>
<template>
    <div class="flex flex-col items-center
  max-sm:w-1/3 sm:w-1/3 md:w-1/4 lg:w-1/6 xl:w-1/12 2xl:w-1/16
  text-center hover:bg-gray-300 cursor-pointer">
        <div class="text-7xl">
            📁
        </div>
        <span class="">
            {{ name.slice(0, -1) }}
        </span>
    </div>
</template>

// front-ng/src/app/dir-item/dir-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FileItem } from '../file-item';
import { PageService } from '../page.service';



@Component({
  selector: 'dir-item',
  standalone: true,
  imports: [],
  templateUrl: './dir-item.component.html',
  styles: ``
})
export class DirItemComponent {


  @Input()
  fileItem!: FileItem;
  constructor(private page:PageService){}
  click(): void {
    this.page.goNextPath(this.fileItem.name);
  }
}

<div
  class="flex flex-col items-center w-24 text-center hover:bg-gray-300 cursor-pointer"
    
  (click)="click()"
>
  <div class="text-7xl">📁</div>
  <span class="">
    {{ fileItem.displayName }}
  </span>
</div>
